feat: RPPL-1067: Port secureStorage manage APIs
rdkcentral/Ripple pull request #240
Opened 2023-09-20 16:29 UTC by bsenth200

## What

What does this PR add or remove?

## Why

Why are these changes needed?

## How

How do these changes achieve the goal?

## Test

How has this been tested? How can a reviewer test it?

## Checklist

- [ ] I have self-reviewed this PR
- [ ] I have added tests that prove the feature works or the fix is effective

2023-09-20 16:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/Ripple?pullRequest=240) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/Ripple?pullRequest=240) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/Ripple?pullRequest=240) it.</sub>

2023-09-21 10:46 UTC, satlead approved these changes
lgtm

2023-09-25 15:22 UTC, SKumarMetro requested changes
Missing #[serde(rename_all = "camelCase")] for  SecureStorageRemoveRequest

2023-09-25 16:07 UTC, SKumarMetro approved these changes

2023-09-25 19:32 UTC, Swati-Chand approved these changes

2023-09-25 20:05 UTC, merged