Fix/ad policy events
rdkcentral/Ripple pull request #270
Opened 2023-10-09 17:40 UTC by brendanobra

## What

This addresses 2 bugs
- Ripple Not emitting advertising.onPolicyChanged when skipRestriction value is changed
- unwrap when thunder call fails, causing panic

## Why

Why are these changes needed?

## How

How do these changes achieve the goal?
- for advertising.onPolicyChanged, an additional (missing) event key was added
- for thunder change, unwrap was replaced with return of empty value 

## Test

Manually against hardware

## Checklist

- [ X] I have self-reviewed this PR
- [ X] I have added tests that prove the feature works or the fix is effective

2023-10-09 17:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/Ripple?pullRequest=270) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/Ripple?pullRequest=270) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/Ripple?pullRequest=270) it.</sub>

2023-10-12 02:50 UTC, satlead approved these changes

2023-10-12 17:45 UTC, Vinodsathyaseelan approved these changes

2023-11-01 20:19 UTC, brendanobra commented on core/main/src/firebolt/handlers/advertising_rpc.rs
> +    pub async fn test_app_bundle_id() {
Adding this as a starting point for one possible approach to testing these handlers.  This does not work for any functions  that are integrated (anything that uses `StorageManager` directly in this case).

2023-11-01 20:20 UTC, brendanobra commented on core/main/src/firebolt/handlers/advertising_rpc.rs
> +    fn merge(a: &mut Value, b: &Value) {
If this is deemed useful, probably good to move it into a util of some sort

2023-11-01 20:20 UTC, brendanobra commented on core/main/src/firebolt/handlers/advertising_rpc.rs
> +        Ok(
More idiomatic and less stuff

2023-11-01 20:20 UTC, brendanobra commented on core/main/src/firebolt/handlers/advertising_rpc.rs
> +        rpc_add_event_listener_with_decorator(
This is the actual bugfix :)

2023-11-01 20:21 UTC, brendanobra commented on core/main/src/firebolt/handlers/advertising_rpc.rs
> +        Ok(serde_json::to_value(get_advertisting_policy(ps).await)?)
More idiomatic and less stuff

2023-11-01 20:21 UTC, brendanobra commented on core/main/src/firebolt/handlers/advertising_rpc.rs
> +        Ok(serde_json::to_value(
More idiomatic and less stuff

2023-11-01 20:21 UTC, brendanobra commented on core/main/src/firebolt/handlers/advertising_rpc.rs
> +async fn get_advertisting_policy(platform_state: &PlatformState) -> AdvertisingPolicy {
free function to cut down on repetition

2023-11-01 20:22 UTC, brendanobra commented on core/sdk/src/api/firebolt/fb_capabilities.rs
> +impl std::fmt::Display for DenyReason {
This makes returning DenyReason much easier over jsonrpc, and is more idiomatic

2023-11-01 22:30 UTC, Vinodsathyaseelan commented on core/main/src/firebolt/handlers/advertising_rpc.rs
> +        limit_ad_tracking: StorageManager::get_bool(
You may need to use the the following function to get limit_ad_tracking
`limit_ad_tracking: !PrivacyImpl::get_allow_app_content_ad_targeting(ps).await;`

2023-11-01 22:33 UTC, Vinodsathyaseelan requested changes
fix needed for limit_ad_tracking.

2023-11-03 18:08 UTC, Vinodsathyaseelan approved these changes

2023-11-03 21:23 UTC, merged