Support non-negotiable public firebolt apis
rdkcentral/Ripple pull request #293
Opened 2023-10-27 23:40 UTC by maggie98choy

## What

Add support for non-negotiable public firebolt APIs

## Why

In the firebolt spec manifest a method can be marked as non-negotiable. For these APIs, we do not enforce any permission checking of capabilities.

## How

How do these changes achieve the goal?

## Test

How has this been tested? How can a reviewer test it?

## Checklist

- [ ] I have self-reviewed this PR
- [ ] I have added tests that prove the feature works or the fix is effective

2023-10-30 21:15 UTC, Vinodsathyaseelan commented on core/main/src/state/cap/generic_cap_state.rs
> +    pub fn clear_non_negotiable_permission(
Can you confirm if this function removes non-negotiable permission from the input permissions list ?

2023-10-30 21:16 UTC, Vinodsathyaseelan requested changes
.

2023-10-31 04:04 UTC, Vinodsathyaseelan commented on core/main/src/firebolt/firebolt_gatekeeper.rs
>              // Couldnt find any capabilities for the method
I think it's not correct to return error with DenyReason::Unsupported for the use case where all the required permission(s) are filtered out due to non-negotiable policy.  In this case, the permission check should return Ok(),
indicating that the required capabilities are permitted.

2023-11-01 21:07 UTC, Vinodsathyaseelan approved these changes

2023-11-07 19:20 UTC, Swati-Chand approved these changes

2023-11-07 19:25 UTC, merged