Resilient Thunder Connection
rdkcentral/Ripple pull request #409
Opened 2024-01-30 00:56 UTC by Vinodsathyaseelan

## What

1. Recreate Ripple Thunder Pool Client and re-connect to Thunder on Thunder restart. 
2. Reset plugin activation state and re-activate various plugins based on the boot up Configuration 
3. Re-subscribe to Thunder events.  

## Why

This changes are needed to restore Thunder session when Thunder process re-starts.

## How

How do these changes achieve the goal?

## Test

How has this been tested? How can a reviewer test it?

## Checklist

- [ ] I have self-reviewed this PR
- [ ] I have added tests that prove the feature works or the fix is effective

2024-02-05 19:27 UTC, satlead requested changes

2024-02-05 19:27 UTC, satlead commented on device/thunder_ripple_sdk/src/client/thunder_plugin.rs
> +const AUTH_SERVICE_CFG: Cfg = Cfg::new("org.rdk.AuthService", true, false);
Remove this

2024-02-05 19:28 UTC, satlead commented on device/thunder_ripple_sdk/src/client/thunder_plugin.rs
> +            AuthService => AUTH_SERVICE_CFG,
Remove this

2024-02-06 05:34 UTC, Vinodsathyaseelan commented on device/thunder_ripple_sdk/src/client/thunder_plugin.rs
> +const AUTH_SERVICE_CFG: Cfg = Cfg::new("org.rdk.AuthService", true, false);
Done.

2024-02-07 18:29 UTC, satlead commented on device/thunder_ripple_sdk/Cargo.toml
> +tokio-tungstenite = { version = "0.17.1", features = ["native-tls"] }
Can we make it a build or test dependency this will add it by default

2024-02-22 16:49 UTC, tfarz123 approved these changes

2024-02-22 21:00 UTC, merged