fix: Add support for Dynamic Plugins
rdkcentral/Ripple pull request #491
Opened 2024-03-29 21:26 UTC by satlead

## What

Some Thunder plugins are created dynamically. Ripple needs to understand these plugins and have support for their activation

## Why

To support Thunder plugins which are added dynamically to the framework.

## How

Uses the existing subscriber mechanism to setup state subscribers and provide the support.

## Test

Using a dynamic app plugin launched by RDKShell.launch

## Checklist

- [ ] I have self-reviewed this PR
- [ ] I have added tests that prove the feature works or the fix is effective

2024-03-29 21:37 UTC, Vinodsathyaseelan commented on device/thunder_ripple_sdk/src/client/thunder_client_pool.rs
> +                    PluginManagerCommand::WaitForActivationForDynamicPlugin { callsign: _, tx } => {
Where is this command used ?

2024-03-29 21:38 UTC, Vinodsathyaseelan commented on device/thunder_ripple_sdk/src/client/plugin_manager.rs
> +                    PluginManagerCommand::WaitForActivationForDynamicPlugin { callsign, tx } => {
Where is this command used ?

2024-03-29 22:17 UTC, Vinodsathyaseelan requested changes
.

2024-03-29 22:30 UTC, Vinodsathyaseelan approved these changes

2024-04-12 18:13 UTC, closed without merging

2024-04-12 18:13 UTC, satlead commented
Duplicate #503