RPPL-1712: Disable opt overrides on prod builds
rdkcentral/Ripple pull request #496
Opened 2024-04-04 00:55 UTC by pkumbh631

## What

What does this PR add or remove?

## Why

Why are these changes needed?

## How

How do these changes achieve the goal?

## Test

How has this been tested? How can a reviewer test it?

## Checklist

- [ ] I have self-reviewed this PR
- [ ] I have added tests that prove the feature works or the fix is effective

2024-04-04 16:33 UTC, Vinodsathyaseelan requested changes

2024-04-04 17:28 UTC, satlead commented on systemd/ripple.service
> +ExecStartPre=/bin/sh -c '. /etc/device.properties; if [ "$BUILD_TYPE" == "prod" ] && [ -f /opt/firebolt-device-manifest.json ];then  RPPLDEVICEMANIFESTFILE=/etc/firebolt-device-manifest.json; /bin/sy
The expectation here is to provide more options on prec-exec to setup manifests on a Pre-prod. Also to run some test cases for post exec. Yes it's the responsibility of the device owner to have a valid script

2024-04-04 17:48 UTC, satlead approved these changes

2024-04-04 17:55 UTC, Vinodsathyaseelan approved these changes

2024-04-10 02:46 UTC, Nv-Delle1416 approved these changes

2024-04-10 20:21 UTC, merged