RPPL-2148 [Storage Broker] Cleanup Localization
rdkcentral/Ripple pull request #568
Opened 2024-07-15 22:11 UTC by sakshihcst

## What

What does this PR add or remove?

## Why

Why are these changes needed?

## How

How do these changes achieve the goal?

## Test

How has this been tested? How can a reviewer test it?

## Checklist

- [ ] I have self-reviewed this PR
- [ ] I have added tests that prove the feature works or the fix is effective

2024-07-16 12:59 UTC, satlead commented on core/main/src/firebolt/handlers/localization_rpc.rs
> +pub async fn get_language(ctx: &CallContext, state: &PlatformState) -> RpcResult<String> {
Why do we need this if there is a rule?

2024-07-16 20:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/Ripple?pullRequest=568) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/Ripple?pullRequest=568) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/Ripple?pullRequest=568) it.</sub>

2024-07-22 22:30 UTC, Vinodsathyaseelan approved these changes

2024-07-23 22:33 UTC, Vinodsathyaseelan requested changes
The usage of `main_internal_request()` call  for `localization.language` from `LoadDistributorValuesStep::setup() -> MetricsState::initialize()`  will cause bootstrap lock up (indefinite wait).  Covert this PR to draft for re-work.

2025-08-15 15:06 UTC, closed without merging